name: 'Zigbee Multi Switch and Childs Mc'
packageKey: 'Zigbee_Multi_Switch-v4'
description: 'Devices: https://github.com/Mariano-Github/Edge-Drivers-Beta/blob/main/zigbee-multi-switch-v3.5/fingerprints.yml'
permissions:
  zigbee: {}
