name: 'Zigbee Power/Meter Mc'
packageKey: 'zigbee-power-meter'
description: 'Devices supported: https://github.com/Mariano-Github/Edge-Drivers-Beta/blob/main/zigbee-multi-switch-v3.5/fingerprints.yml'
permissions:
  zigbee: {}
